# Generated by Django 5.0.3 on 2024-03-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.BigIntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(default=9999),
        ),
    ]
