# Generated by Django 5.0.3 on 2024-03-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_branch_student_email_student_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(default='none', max_length=30, primary_key=True, serialize=False),
        ),
    ]
