# Generated by Django 5.0.3 on 2024-03-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_subject_student_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(default='Stu-001', max_length=30),
        ),
    ]
